version: '3.7'

services:
  traefik:
    image: traefik:v2.11
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker.exposedByDefault=false"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    labels:
      - "traefik.http.routers.traefik.rule=Host(`traefik.localhost`) && PathPrefix(`/dashboard`)"
      - "traefik.http.routers.traefik.middlewares=dashboard-stripprefix"
      - "traefik.http.middlewares.traefik-stripprefix.stripprefix.prefixes=/dashboard"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.services.dashboard.loadbalancer.server.port=8080"
    networks:
      - traefik-network

  golangapi:
    build:
      context: ./golang-api #get from apps
    image: golang-api
    ports:
      - "8020"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.golangapi.rule=Host(`traefik.localhost`) && PathPrefix(`/golangapi`)"
      - "traefik.http.routers.golangapi.middlewares=golangapi-stripprefix"
      - "traefik.http.middlewares.golangapi-stripprefix.stripprefix.prefixes=/golangapi"
      - "traefik.http.services.golangapi.loadbalancer.server.port=8020"
    volumes:
      - ./golang-api:/go/src/app
    networks:
      - traefik-network

  nodeapi:
    build:
      context: ./node-api
    image: nodejs
    ports:
      - "8030"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nodeapi.rule=Host(`traefik.localhost`) && PathPrefix(`/api`)"
      - "traefik.http.routers.nodeapi.middlewares=nodeapi-stripprefix"
      - "traefik.http.middlewares.nodeapi-stripprefix.stripprefix.prefixes=/api"
      - "traefik.http.services.nodeapi.loadbalancer.server.port=8030"
    volumes:
      - ./node-api:/app
      - ./node_modules:/app/node_modules
    networks:
      - traefik-network

  jsonserver:
    build:
      context: ./jsonserver
      dockerfile: Dockerfile
    ports:
      - "3100"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jsonserver.rule=Host(`traefik.localhost`) && PathPrefix(`/jsonserver`)"
      - "traefik.http.routers.jsonserver.middlewares=jsonserver-stripprefix"
      - "traefik.http.middlewares.jsonserver-stripprefix.stripprefix.prefixes=/jsonserver"
      - "traefik.http.services.jsonserver.loadbalancer.server.port=3100"
    volumes:
      - ./jsonserver/db.json:/app/db.json
    networks:
      - traefik-network

networks:
  traefik-network:
